// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zeldhmbgpzdmxysnpjhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplbGRobWJncHpkbXh5c25wamhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcxMzIzNDUsImV4cCI6MjA1MjcwODM0NX0.rR2mIaBM-Js_-ci3Rk6WE79c_yGV6u9sPErE6lPxiU8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);